Repository webb-tools/protocol-substrate, pull requests merged in 2022-05, with the labels that each got.

#196 Reworks anchor system pallets to match Solidity implementation
  Cargo.lock
  client/Cargo.toml
  client/tests/utils.rs
  node/Cargo.toml
  pallets/anchor-handler/Cargo.toml
  pallets/anchor-handler/src/mock_bridge.rs
  pallets/anchor-handler/src/mock_signature_bridge.rs
  pallets/anchor-handler/src/tests_bridge.rs
  pallets/anchor-handler/src/tests_signature_bridge.rs
  pallets/anchor/Cargo.toml
  pallets/anchor/src/lib.rs
  pallets/anchor/src/mock.rs
  pallets/anchor/src/test_utils.rs
  pallets/anchor/src/tests.rs
  pallets/hasher/Cargo.toml
  pallets/hasher/src/lib.rs
  pallets/hasher/src/tests.rs
  pallets/linkable-tree/Cargo.toml
  pallets/linkable-tree/src/lib.rs
  pallets/linkable-tree/src/mock.rs
  pallets/linkable-tree/src/tests.rs
  pallets/mixer/Cargo.toml
  pallets/mixer/src/lib.rs
  pallets/mixer/src/mock.rs
  pallets/mixer/src/test_utils.rs
  pallets/mixer/src/tests.rs
  pallets/mt/Cargo.toml
  pallets/mt/src/lib.rs
  pallets/mt/src/mock.rs
  pallets/mt/src/tests.rs
  pallets/signature-bridge/src/tests.rs
  pallets/token-wrapper-handler/src/tests_bridge.rs
  pallets/vanchor/Cargo.toml
  pallets/vanchor/src/lib.rs
  pallets/vanchor/src/mock.rs
  pallets/vanchor/src/test_utils.rs
  pallets/verifier/src/lib.rs
  pallets/xanchor/Cargo.toml
  pallets/xanchor/src/lib.rs
  pallets/xanchor/src/mock/parachain.rs
  primitives/src/utils.rs
  runtime/src/lib.rs
  standalone/node/Cargo.toml
  standalone/node/src/chain_spec.rs
  standalone/runtime/src/lib.rs
Labels: wip 🚧

#207 Test webb-proposals for substrate
  pallets/anchor-handler/Cargo.toml
  pallets/anchor-handler/src/tests_signature_bridge.rs
  pallets/token-wrapper-handler/Cargo.toml
  pallets/token-wrapper-handler/src/tests_signature_bridge.rs
  pallets/xanchor/Cargo.toml
  pallets/xanchor/src/lib.rs
  pallets/xanchor/src/tests.rs
  primitives/Cargo.toml
Labels: approved ✅, needs review 👓

#211 update webb-proposals tests and add pallet-signature-bridge to runtime #209
  pallets/anchor-handler/Cargo.toml
  pallets/anchor-handler/src/tests_signature_bridge.rs
  pallets/token-wrapper-handler/Cargo.toml
  pallets/token-wrapper-handler/src/tests_signature_bridge.rs
  pallets/xanchor/Cargo.toml
  pallets/xanchor/src/lib.rs
  pallets/xanchor/src/tests.rs
  primitives/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
  standalone/runtime/Cargo.toml
  standalone/runtime/src/lib.rs
Labels: approved ✅

#216 Make `AssetNativeLocation` of type `u32`
  standalone/runtime/src/lib.rs
Labels: needs review 👓
